name: "composite with inputs action"
description: "composite with inputs action"

inputs:
  some:
    description: "some input"
    required: true
  other:
    description: "other input"
    default: value
    required: false
outputs:
  output:
    description: "some output"
    value: "value"

runs:
  using: "composite"
  steps:
    - run: |
        echo "${{toJSON(inputs)}}"
      shell: bash
