name: Gitea Actions Test
run-name: ${{ github.actor }} is testing out Gitea Actions  
on: [push]
jobs:
  Explore-Gitea-Actions:
    needs: Test-Node
    runs-on: ubuntu-latest
    steps:
      - run: echo "  The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "  This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "  The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "  The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " ️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "  This job's status is ${{ job.status }}."

  Test-Docker:
    needs: [Test-Node, Explore-Gitea-Actions]
    runs-on: ubuntu-latest
    # 此容器可使用docker，可查看 https://github.com/catthehacker/docker_images
    # container: catthehacker/ubuntu:act-latest
    steps:
      - run: docker version

  Test-Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # 安装node环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          node -v

      - name: Restore Yarn Cache
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-yarn-
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          npm i
  Test-Empty:
    needs: [Test-Other]
    runs-on: ubuntu-latest
    # 此容器可使用docker，可查看 https://github.com/catthehacker/docker_images
    # container: catthehacker/ubuntu:act-latest
    steps:
      - run: docker version