name: Gitea Actions Test
run-name: ${{ github.actor }} is testing out Gitea Actions  
on: [push]
jobs:
  Test-Empty:
    needs: [Test-Other]
    runs-on: ubuntu-latest
    # 此容器可使用docker，可查看 https://github.com/catthehacker/docker_images
    # container: catthehacker/ubuntu:act-latest
    steps:
      - run: docker version