name: Test Composite Action

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  local-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composite Action
        id: composite_action
        uses: ./test/actions/hello-world-composite-action
        with:
          who-to-greet: 'Composite!'

      - name: Get the Composite Action output random number
        run: echo "The random number was ${{ steps.composite_action.outputs.random-number }}"
