name: uses-composite-with-error
on: workflow_dispatch

jobs:
  failing-composite-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/composite-with-error
    - run: echo should run
      if: failure()
    - run: echo should not run
