name: basic
on: push

env:
  TEST: value

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: '[[ "$(pwd)" == "${GITHUB_WORKSPACE}" ]]'
      - run: echo ${{ env.TEST }} | grep value
      - run: env
      - uses: docker://alpine:latest
        with:
          somekey: ${{ env.TEST }}
          args: echo ${INPUT_SOMEKEY} | grep somevalue
      - run: ls
      - run: echo 'hello world'
      - run: echo ${GITHUB_SHA} >> $(dirname "${GITHUB_WORKSPACE}")/sha.txt
      - run: cat $(dirname "${GITHUB_WORKSPACE}")/sha.txt | grep ${GITHUB_SHA}
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      # - uses: ./test/actions/hello-world-javascript-action
      #   with:
      #     args: echo 'build'
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: docker://alpine:latest
        with:
          args: env
      - uses: docker://alpine:latest
        with:
          entrypoint: /bin/echo
          args: ${{github.event_name}}
