name: Call Reusable

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  job1:
    uses: ./.github/workflows/reusable.yml
    with:
      username: 'actions test'
    secrets:
      access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print needs.jobId
        run: echo "${{ toJson(needs.job1) }}"
      - name: Print jobs
        run: echo ${{ job.status }}
