name: matrix
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
      output_2: ${{ steps.gen_output.outputs.output_2 }}
      output_3: ${{ steps.gen_output.outputs.output_3 }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output_1=${version}" >> "$GITHUB_OUTPUT"
      - name: Print strategy
        run: |
          echo "strategy.job-total=${{strategy.job-total}}"
          echo "strategy.job-index=${{strategy.job-index}}"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      # Will show
      # {
      #   "output_1": "1",
      #   "output_2": "2",
      #   "output_3": "3"
      # }
      - name: Print job outputs
        run: echo '${{ toJSON(needs.job1.outputs) }}'

      - name: Print strategy
        run: |
          echo "strategy=${{toJSON(strategy)}}"