name: call reusable workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  job1:
    uses: ./.github/workflows/reusable.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print needs.jobId
        run: echo "${{ toJson(needs.job1) }}"
      - name: Print jobs
        run: echo ${{ job.status }}
